#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=20
#PBS -N fic50topic
#PBS -q ichass
#PBS -m be
cd $PBS_O_WORKDIR
module load java/1.8
bin/mallet train-topics --input ../code/chartopics/data/basicficchars.mallet --num-threads 18 --num-topics 50 --num-iterations 1900 --num-top-words 80 --random-seed 99 --optimize-interval 25 --optimize-burn-in 50 --output-state ../code/chartopics/fic50topic/modelstate.gz --output-doc-topics ../code/chartopics/fic50topic/fic50topic_doctopics.txt --output-topic-keys ../code/chartopics/fic50topic/fic50topic_keys.txt --inferencer-filename ../code/chartopics/fic50topic/inferencer.bin --show-topics-interval 100
