#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=20
#PBS -N fic100topic
#PBS -q ichass
#PBS -m be
cd $PBS_O_WORKDIR
module load java/1.8
bin/mallet train-topics --input ../code/chartopics/data/basicficchars.mallet --num-threads 18 --num-topics 100 --num-iterations 2000 --num-top-words 80 --random-seed 99 --optimize-interval 25 --optimize-burn-in 100 --output-state ../code/chartopics/fic100topic/modelstate.gz --output-doc-topics ../code/chartopics/fic100topic/fic100topic_doctopics.txt --output-topic-keys ../code/chartopics/fic100topic/fic100topic_keys.txt --inferencer-filename ../code/chartopics/fic100topic/inferencer.bin --show-topics-interval 200
