#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=20
#PBS -N bio200topic
#PBS -q ichass
#PBS -m be
cd $PBS_O_WORKDIR
module load java/1.8
bin/mallet train-topics --input ../code/biographies/topicmodel/data/biochars.mallet --num-threads 18 --num-topics 200 --num-iterations 2500 --num-top-words 80 --random-seed 99 --optimize-interval 25 --optimize-burn-in 150 --output-state ../code/biographies/topicmodel/bio200/modelstate.gz --output-doc-topics ../code/biographies/topicmodel/bio200/bio200_doctopics.txt --output-topic-keys ../code/biographies/topicmodel/bio200/bio200_keys.txt --inferencer-filename ../code/biographies/topicmodel/bio200/inferencer.bin --show-topics-interval 100
