#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=20
#PBS -N ficnospeech50topic
#PBS -q ichass
#PBS -m be
cd $PBS_O_WORKDIR
module load java/1.8
bin/mallet train-topics --input ../code/chartopics/data/ficnospeech.mallet --num-threads 18 --num-topics 50 --num-iterations 2500 --num-top-words 80 --random-seed 99 --optimize-interval 25 --optimize-burn-in 150 --output-state ../code/chartopics/ficnospeech50/modelstate.gz --output-doc-topics ../code/chartopics/ficnospeech50/ficnospeech50_doctopics.txt --output-topic-keys ../code/chartopics/ficnospeech50/ficnospeech50_keys.txt --inferencer-filename ../code/chartopics/ficnospeech50/inferencer.bin --show-topics-interval 200
